name: cygwin

on: [ push, pull_request ]

env:
  CASE_INSENSITIVE: 1
  
jobs:
  toolchain:
    runs-on: windows-latest
    
    steps:
    - name: Turn off line ending conversion in git
      run: |
        git config --global core.autocrltf false
        git config --global core.eol lf
        
    - uses: actions/checkout@v1
    
    - uses: actions/cache@v3
      with:
        path: C:\cygwin-packages
        key: cygwin-packages-${{ hashFiles('C:\cygwin-packages\**') }}
        restore-keys: cygwin-packages-
        
    - name: Fetch Cygwin installer
      run: Invoke-WebRequest https://cygwin.com/setup-x86_64.exe -OutFile C:\setup.exe
      shell: powershell
      
    # installer should be cacheable
    - name: Install Cygwin
      run:  |
        c:\setup -qgnO -s https://cygwin.itefix.net -l C:\cygwin-packages\ -P ^
        autoconf,^
        autogen,^
        automake,^
        binutils,^
        bison,^
        dos2unix,^
        flex,^
        gawk,^
        gcc-g++,^
        gettext,^
        gettext-devel,^
        git,^
        git-archive-all,^
        help2man,^
        libcrypt-devel,^
        libiconv-devel,^
        libgmp-devel,^
        libmpc-devel,^
        libmpfr-devel,^
        libncurses-devel,^
        make,^
        patch,^
        perl-File-ShareDir,^
        perl-Unicode-Normalize,^
        python38-devel,^
        python27-wheel,^
        python37-pip,^
        python37-setuptools,^
        python37-wheel,^
        python38-pip,^
        python38-setuptools,^
        python38-wheel,^
        python38-pygments,^
        python39-pip,^
        python39-setuptools,^
        python39-wheel,^
        terminfo,^
        texlive-collection-latex,^
        texinfo,^
        texinfo-tex
      shell: cmd
      
    - name: Set PATH
      run: echo "PATH=C:\cygwin64\bin;C:\cygwin64\lib\lapack;C:\cygwin64\usr\local\cross-tools\bin;C:\cygwin64\usr\local\cross-tools\x86_64-pc-linux-gnu\bin;%SYSTEMROOT%\system32" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
    - name: Fixup Cygwin installation
      run: |
        bash --login
        bash -c '/usr/sbin/alternatives --set python /usr/bin/python3.8'
        bash -c '/usr/sbin/alternatives --set python3 /usr/bin/python3.8'
        bash -c '/usr/sbin/alternatives --set python3-config /usr/bin/python3.8-config'
        bash -c 'sed -i s#/usr/bin/python\$#/usr/bin/python3.9# /usr/bin/pip3.9'
        bash -c 'sed -i s@#!/bin/python\$@#!/bin/python2@ /usr/bin/bzr'
        bash -c 'git config --system --add safe.directory /cygdrive/d/a/cygport/cygport'
        bash -c 'git config --system --add safe.directory /cygdrive/d/a/cygport/cygport/data/gnuconfig'
      continue-on-error: true
      
    - name: Build
      run: |
        bash -c 'dos2unix build.sh'
        bash build.sh
        
